language: python
python:
- '3.4'
- '3.5'
matrix:
  include:
  - python: 3.7
    dist: xenial
    sudo: true
  - python: 3.6
    script: travis_retry coverage run -m pytest && coveralls
install:
- pip install masonite_cli
- pip install -e .[hashids]
- pip install -r requirements.txt
script:
- travis_retry coverage run -m pytest
- flake8 masonite/ --ignore=E501,F401,E128,E402,E731,F821,E712,W503
deploy:
  provider: pypi
  user: josephmancuso
  password:
    secure: b8zaj+TpSQ0C3b1UqqrWBQ0kKGuirPxnJIamOu92AVlIt3B75zS61vQDdMlkeQAffrwbggZYAF3KaZRrG9YHSsV3SpYjIWpij8UU0eihLvbQaR1lUdHWLelzYJ71E69Eu5ix1Eb3XW3vKx9fBjROsoWQttSKOcHTdsjMClc8RF5Fj+RlnHQVewzlIkzgxfYdPnxlNXe3vc4Oqa2dpfg/db32NavnyBnK4xzvDhHCUO0wcXwi4qmP7ONMcde/uFyYxILu6WEY8l4kDQELjjHfogBWgAQBGFe/JpqNuZDHj9xptg8fULqvNG2ubG/dYQbiEZAb5Q72sfw2O1fV+UEI6M2hJjU2877aN8PsFahOiogd0LM1rhl37t6qS+/PFAg4i57DJqlJrGEB5/CFskMO0K31K1SaLEQSrhTv0AQQyAJI7bgzLDKPwpdan1b3Ehmup9b4WEO5weMo1RfEjDqy5YT/NDAPCxpj7WEoKeBqnwFFnLSCe7XdS1I93yK3cUThB2GTna7mIroaR3hd9QnWS0GSWXRMAkG5Hg9seKjJgltkIl6+c4N60jv7LdiKGLc/BI0sajxp7pkFeOzfEZDj1gzjN8KfJM9kgDB1r39cXtHqi1Q4yJfJIygvXQPMk+rSPKDgv+uuZwnyCBKrziJ1/gcgAyIaIBLsfAaVhW/6cVQ=
  on:
    tags: true
    python: 3.6
